In [6]:
# with open('./drive/MyDrive/ReadMe.md','w') as f:
#   data = f.write('반가워요')
#   print('저장되었습니다.')
# !pwd

# 넘파이(numpy)

- ndim  : 축의 개수
- shape : 배열의 차원 정보
- size  : 배열 안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형


## 1차원과 속성들

In [1]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry, type(narry))
# numpy의 배열은 ,가 없다
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[3])
print(narry[2:4])
print(narry.dtype)

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
3
[2 3]
int64


In [24]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [76]:
narr4 = np.zeros(5)
# ,가 아님에 주의!
# 배열을 초기화 할 때 많이 씀
narr5 = np.zeros(5, dtype='int64')
narr6 = np.zeros((2,2), dtype='int64')
narr7 = np.full((3,3),3)
narr8 = np.ones((2,2))
narr9 = np.full((3,3),'num')
narr10 = np.eye(3)
narr11 = np. linspace(0,100,5, endpoint=False, dtype='int64')
narr12 = np.arange(0,100,20)
print('narr4:', narr4,narr4.ndim, narr4.dtype, narr4.shape, narr4.size,type(narr4))
print('narr5:', narr5,narr5.ndim, narr5.dtype, narr5.shape, narr5.size,type(narr5))
print('narr6:', narr6,narr6.ndim, narr6.dtype, narr6.shape, narr6.size,type(narr6))
print('narr7:', narr7,narr7.ndim, narr7.dtype, narr7.shape, narr7.size,type(narr7))
print('narr8:', narr8,narr8.ndim, narr8.dtype, narr8.shape, narr8.size,type(narr8))
print('narr9:', narr9,narr9.ndim, narr9.dtype, narr9.shape, narr9.size,type(narr9))
print('narr10:', narr10,narr10.ndim, narr10.dtype, narr10.shape, narr10.size,type(narr10))
print('narr11:', narr11,narr11.ndim, narr11.dtype, narr11.shape, narr11.size,type(narr11))
print('narr12:', narr12,narr12.ndim, narr12.dtype, narr12.shape, narr12.size,type(narr12))

narr4: [0. 0. 0. 0. 0.] 1 float64 (5,) 5 <class 'numpy.ndarray'>
narr5: [0 0 0 0 0] 1 int64 (5,) 5 <class 'numpy.ndarray'>
narr6: [[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
narr7: [[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
narr8: [[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
narr9: [['num' 'num' 'num']
 ['num' 'num' 'num']
 ['num' 'num' 'num']] 2 <U3 (3, 3) 9 <class 'numpy.ndarray'>
narr10: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
narr11: [ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
narr12: [ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [49]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr1 = np.array([0,0,0])
arr2 = np.array([[0,0],[0,0]])
print(arr1)
print(arr2, arr2.ndim, arr2.dtype, arr2.shape, arr2.size, type(arr2))

[0 0 0]
[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [56]:
arr3 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr4 = np.arange(1,10).reshape(3,3)
arr5 = np.arange(1,11).reshape(2,5)
arr6 = np.arange(1,11).reshape(5,2)
arr7 = np.arange(1,28).reshape(3,3,3)
print('arr3:','차원:', arr3.ndim, '데이터타입:', arr3.dtype, '형태:',arr3.shape, '크기:',arr3.size, type(arr3), arr3)
print('arr4:','차원:', arr4.ndim, '데이터타입:', arr4.dtype, '형태:',arr4.shape, '크기:',arr4.size, type(arr4), arr4)
print('arr5:','차원:', arr5.ndim, '데이터타입:', arr5.dtype, '형태:',arr5.shape, '크기:',arr5.size, type(arr5), arr5)
print('arr6:','차원:', arr6.ndim, '데이터타입:', arr6.dtype, '형태:',arr6.shape, '크기:',arr6.size, type(arr6), arr6)
print('arr7:','차원:', arr7.ndim, '데이터타입:', arr7.dtype, '형태:',arr7.shape, '크기:',arr7.size, type(arr7), arr7)

arr3: 차원: 2 데이터타입: int64 형태: (3, 3) 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr4: 차원: 2 데이터타입: int64 형태: (3, 3) 크기: 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr5: 차원: 2 데이터타입: int64 형태: (2, 5) 크기: 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
arr6: 차원: 2 데이터타입: int64 형태: (5, 2) 크기: 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
arr7: 차원: 3 데이터타입: int64 형태: (3, 3, 3) 크기: 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [72]:
a1 = np.arange(1,22).reshape(3,7)
print(a1)
print('-'*20)
a2 = np.arange(1,8).reshape(7,1)
print(a2)
print('-'*20)
a3 = np.arange(1,11).reshape(5,2)
print(a3)
print('-'*20)
a4 = np.arange(1,22).reshape(3,7)
print(a4)
print('-'*20)
a5 = np.arange(1,13).reshape(4,3,1)
print(a5)
# print('-'*20)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
--------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
--------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
--------------------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
--------------------
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [81]:
a1[1][2:5]

array([10, 11, 12])

In [110]:
a4[0][3:]
# a4[1][3:]
# a4[2][3:]
print('[',a4[0][3:], a4[1][3:], a4[2][3:],']')
print(a4[0:3,3:])
a4[1:3,4:6]

[ [4 5 6 7] [11 12 13 14] [18 19 20 21] ]
[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]


array([[12, 13],
       [19, 20]])

In [111]:
a4[a4>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [112]:
[a4>12]

[array([[False, False, False, False, False, False, False],
        [False, False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True]])]

In [116]:
a4 % 2 == 0

array([[False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])

In [121]:
# np 배열 연산 //  shape가 같은 경우 원소별 연산이 가능
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print('덧셈:', np1 + np2)
print('뺄셈:', np1 - np2)
print('곱셈:', np1 * np2)
print('나눗셈:', np1 / np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [-5 -5 -5 -5 -5]
곱셈: [ 6 14 24 36 50]
나눗셈: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [124]:
# 브로드캐스팅: 전역적으로 다른 크기의 배열을 연산함
np3 = np1 + 10
print(np3)

[11 12 13 14 15]


In [133]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]).reshape(1,3)
# br2 = np.array([11,22,33]).reshape(3,1)
# 스칼라와 연산
print('------스칼라와 연산------')
print(br1)
print(br1+3)
print(br1*2)
# 1D와 2D의 연산
print('------1D와 2D의 연산------')
print(br2)
print(br1+br2)
print(br1*br2)

------스칼라와 연산------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
------1D와 2D의 연산------
[[11 22 33]]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [135]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(1,9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint() : 균일 분포의 정수 난수
- np.random.rand()    : 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(    : 표준 정규 분포 난수 생성
- np.random.normal()  : 정규 분포 난수 생성

In [4]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[ 49,  24, 115],
        [253, 140,  38],
        [101, 242, 239]],

       [[244, 195,  94],
        [ 32,  54,  38],
        [146,  50, 152]],

       [[151, 118, 172],
        [222, 232, 120],
        [247,  68, 176]]], dtype=int32)

In [6]:
print('평균값:', np.mean(x),'표준편차:', np.std(x),'최소값:', x.min(),'최대값:', x.max())

평균값: 137.4814814814815 표준편차: 75.99628176594996 최소값: 24 최대값: 253


In [7]:
print(len(x.flatten()))

27


In [12]:
y = np.array([0,1,2,3,4,6,4,51,421,78,851,1,0,0,45,12,45,21,3,465,14,5,45,1,78,5,9]).reshape(3,3,3)
# count_nonzero(x)

print(len(y))
print((np.count_nonzero(y)))

3
24


# 판다스(Pandas)

- 시리즈(serises)
- 데이터프레임(dataframe)

In [2]:
# !pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [22]:
# 판다스 기초
data1 = np.arange(1,11)
print(data1)
data2 = pd.Series(data1)
print(data2,'/', type(data2),'/', data2.index,'/', data2.values,'/', data2.dtype) #data2.values는 pandas에 넣기 전의 값을 보여줌

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 / <class 'pandas.core.series.Series'> / RangeIndex(start=0, stop=10, step=1) / [ 1  2  3  4  5  6  7  8  9 10] / int64


In [20]:
# 판다스 시리즈의 데이터타입
data3 = pd.Series([1,2,3,4,5,6,7]) #, dtype='float')
print(data3)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [21]:
# 판다스 시리즈의 데이터타입
data3 = pd.Series([1,2,3.14,4,5,6,7]) #, dtype='float')
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [18]:
# 판다스 시리즈의 인덱스 설정
data3 = pd.Series([1,2,3,4] , index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [136]:
# 판다스 시리즈 딕셔너리데이터
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa': 32976
}
# print(population_dict.keys()) == country.index
# .(온점) 뒤에 오는 함수 뒤에 ()가 있으면 어떠한 행위를 할 것을 의미함
# print(population_dict.values())
# print(population_dict.items())
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근 방법
print(country.loc['korea']) # location이라는 뜻
print(country.iloc[0])      # index location

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
5182
5182


In [45]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=['a','b','c'], columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [137]:
# 테스트
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터
print('인구수 시리즈 데이터:')
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa': 32976
}
population = pd.Series(population_dict)
print(population)

# ctrl shift d
print('GDP 시리즈 데이터:')
GDP_dict = {
   'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa': 2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('-'*25)

print('데이터 프레임 생성:')
country = pd.DataFrame({'population':population, 'gdp':GDP})
country.index.name='Country' # 인덱스 이름 지정
country.columns.name='Info'  # 컬럼 이름 지정
print(country.index, '\n', country.columns, '\n', country.values)
print(country.shape, country.size, country.ndim)


인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
-------------------------
데이터 프레임 생성:
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') 
 Index(['population', 'gdp'], dtype='object', name='Info') 
 [[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]]
(4, 2) 8 2


In [138]:
country

Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [139]:
# 데이터 프레임의 요소 접근 방법, loc, iloc
country.loc['korea'], country.loc['usa']
country.iloc[2], country.iloc[1]

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [140]:
country.loc['korea':'china', :'population']
# 이전 list 에는 <= x < 였음
# 지금은 <= x <= 임

Info     population
Country            
korea          5182
japan         12622
china        141178

In [141]:
country.iloc[0:3, :1]
# loc는 <= x < 
# iloc는 <= x <= 

Info     population
Country            
korea          5182
japan         12622
china        141178

In [142]:
country.iloc[1:4, 1:2]

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [143]:
country.iloc[1:3, :2]

Info     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [144]:
# # 컬럼 추가
# country['test'] = [11,22,33,44]
# country = country.drop('test', axis=1) #행 삭제
gdpper = country['gdp'] / country ['population']
country['gdp_per']= gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [145]:
# 행추가 방법1
country.loc['india'] = [1479619, 150505000,'NaN']
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india       1479619   150505000    101.718753

In [159]:
# 행추가 방법2
africa = pd.Series(data = [123456,7777777],index=['population','gdp'])
country.loc['africa'] = africa
# country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india     1479619.0  1.505050e+08    101.718753
africa     123456.0  7.777777e+06           NaN

In [160]:
# 결측값(NaN) 확인하는 방법
country.isnull()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
africa        False  False     True

In [161]:
country.isnull().sum()

Info
population    0
gdp           0
gdp_per       1
dtype: int64

In [162]:
# 열 제거 drop(이름, axis=0 )
country= country.drop('africa',axis=0) # inplace = true
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india     1479619.0  1.505050e+08    101.718753

In [165]:
#테스트1 조건
country[country['population'] > 140000]

Info     population          gdp     gdp_per
Country                                     
china      141178.0  140925000.0  998.207936
india     1479619.0  150505000.0  101.718753

In [168]:
#테스트2 조건, 슬라이싱(loc,iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

In [3]:
import numpy as np
import pandas as pd

name={}

kor = {
    '홍길동':80,
    '박철수':60,
    '김영희':70
}

mat = {
    '홍길동':70,
    '박철수':70,
    '김영희':90
}

eng = {
    '홍길동':80,
    '박철수':80,
    '김영희':80
}


# student = pd.DataFrame(index=[0,1,2], columns=['이름'])
student = pd.DataFrame({'국어':kor, '수학':mat, '영어':eng})
student


국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [183]:
student.iloc[1:2, :2]

국어  수학
박철수  60  70

In [190]:
student[(student['수학'] >= 70)]

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [209]:
sum = student['국어'] + student['수학']+ student['영어']
student['총합']= sum
avg = (student['총합'] / 3)
student['평균']= avg
student

국어    수학    영어     총합         평균
홍길동  80.0  70.0  80.0  230.0  76.666667
박철수  60.0  70.0  80.0  210.0  70.000000
김영희  70.0  90.0  80.0  240.0  80.000000
최자바  55.0  95.0  70.0  220.0  73.333333

In [213]:
최자바 = pd.Series(data = [55,95,70],index=['국어','수학','영어'])
student

국어    수학    영어     총합         평균
홍길동  80.0  70.0  80.0  230.0  76.666667
박철수  60.0  70.0  80.0  210.0  70.000000
김영희  70.0  90.0  80.0  240.0  80.000000
최자바  55.0  95.0  70.0  220.0  73.333333